services:
  db:
    image: postgres:16
    container_name: finances_db
    restart: always
    environment:
      POSTGRES_USER: finances_db
      POSTGRES_PASSWORD: finances_db
      POSTGRES_DB: finances_db
    ports:
      - "5432:5432"
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
